-- Ana Carolina Pereira Fontes, RM562145
-- Daniel Nicolas Leoterio, RM562186
-- Matheus Moya de Oliveira, RM562822

-- CRIANDO T_HC_PACIENTE
CREATE TABLE T_HC_PACIENTE (
    ID_PACIENTE CHAR(5),
    NM_PACIENTE CHAR(50),
    NR_CPF CHAR(15),
    NR_RG CHAR(13),
    NR_ALTURA NUMBER,
    NR_PESO NUMBER,
    DT_NASCIMENTO DATE,
    DS_ESCOLARIDADE CHAR(50),
    DS_ESTADO_CIVIL CHAR(50),
    DS_DESCRICAO CHAR(100)
);

-- CRIANDO T_HC_ENDERECO
CREATE TABLE T_HC_ENDERECO(
    ID_ENDERECO CHAR(5),
    NM_LOGRADOURO CHAR(100),
    NR_LOGRADOURO NUMBER,
    NR_CEP CHAR(9),
    NM_BAIRRO CHAR(50),
    NM_CIDADE CHAR(50),
    NM_ESTADO CHAR(20),
    SG_ESTADO CHAR(2),
    DS_COMPLEMENTO CHAR(100),
    DS_PONTO_REFERENCIA CHAR(100)
);

-- CRIANDO T_HC_TELEFONE
CREATE TABLE T_HC_TELEFONE(
    ID_TELEFONE CHAR(5),
    NR_DDI CHAR(3),
    NR_DDD CHAR(2),
    NR_TELEDONE CHAR(10)
);

-- CRIANDO T_HC_CONSULTA
CREATE TABLE T_HC_CONSULTA(
    ID_CONSULTA CHAR(5),
    DT_HR_CONSULTA DATE,
    DS_MODALIDADE CHAR(20)
);

-- CRIANDO T_HC_MEDICO
CREATE TABLE T_HC_MEDICO(
    ID_MEDICO CHAR(5),
    NM_MEDICO CHAR(30),
    NR_CRM CHAR(10)
);

-- CRIANDO T_HC_LEMBRETE
CREATE TABLE T_HC_LEMBRETE(
    ID_LEMBRETE CHAR(5),
    DT_HR_LEMBRETE DATE,
    DS_MODALIDADE CHAR(20),
    DS_MENSAGEM CHAR(100)
);

-- CRIANDO T_HC_CONEXAO
CREATE TABLE T_HC_CONEXAO(
    ID_CONEXAO CHAR(5),
    MD_DISPOSITIVO CHAR(50),
    TP_DISPOSITIVO CHAR(20),
    TP_CONEXAO CHAR(20)
);

-- ALTERANDO TABELAS 
ALTER TABLE T_HC_ENDERECO ADD ID_PACIENTE CHAR(8);
ALTER TABLE T_HC_TELEFONE ADD ID_PACIENTE CHAR(8);
ALTER TABLE T_HC_LEMBRETE ADD ID_PACIENTE CHAR(8);
ALTER TABLE T_HC_CONSULTA ADD ID_PACIENTE CHAR(8);
ALTER TABLE T_HC_CONSULTA ADD ID_MEDICO CHAR(8);
ALTER TABLE T_HC_CONEXAO DROP COLUMN ID_PACIENTE;
ALTER TABLE T_HC_CONSULTA ADD ID_CONEXAO CHAR(8);
ALTER TABLE T_HC_CONSULTA ADD ID_PACIENTE CHAR(8);


--ADICIONANDO PRIMARY KEYS
ALTER TABLE T_HC_PACIENTE ADD CONSTRAINT PK_PACIENTE PRIMARY KEY(ID_PACIENTE);
ALTER TABLE T_HC_ENDERECO ADD CONSTRAINT PK_ENDERECO PRIMARY KEY(ID_ENDERECO);
ALTER TABLE T_HC_TELEFONE ADD CONSTRAINT PK_TELEFONE PRIMARY KEY(ID_TELEFONE);
ALTER TABLE T_HC_CONSULTA ADD CONSTRAINT PK_CONSULTA PRIMARY KEY(ID_CONSULTA);
ALTER TABLE T_HC_MEDICO ADD CONSTRAINT PK_MEDICO PRIMARY KEY(ID_MEDICO);
ALTER TABLE T_HC_LEMBRETE ADD CONSTRAINT PK_LEMBRETE PRIMARY KEY(ID_LEMBRETE);
ALTER TABLE T_HC_CONEXAO ADD CONSTRAINT PK_CONEXAO PRIMARY KEY(ID_CONEXAO);

--ADICIONANDO FOREIGN KEYS
ALTER TABLE T_HC_ENDERECO ADD CONSTRAINT FK_ENDERECO_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES T_HC_PACIENTE(ID_PACIENTE);
ALTER TABLE T_HC_TELEFONE ADD CONSTRAINT FK_TELEFONE_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES T_HC_PACIENTE(ID_PACIENTE);
ALTER TABLE T_HC_CONSULTA ADD CONSTRAINT FK_CONSULTA_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES T_HC_PACIENTE(ID_PACIENTE);
ALTER TABLE T_HC_LEMBRETE ADD CONSTRAINT FK_LEMBRETE_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES T_HC_PACIENTE(ID_PACIENTE);
ALTER TABLE T_HC_CONSULTA ADD CONSTRAINT FK_CONSULTA_CONEXAO FOREIGN KEY (ID_CONEXAO) REFERENCES T_HC_CONEXAO(ID_CONEXAO);
ALTER TABLE T_HC_CONSULTA ADD CONSTRAINT FK_CONSULTA_MEDICO FOREIGN KEY (ID_MEDICO) REFERENCES T_HC_MEDICO(ID_MEDICO);

--ADICIONANDO AS UNIQUES
ALTER TABLE T_HC_PACIENTE ADD CONSTRAINT UN_PACIENTE_CPF UNIQUE (NR_CPF);
ALTER TABLE T_HC_PACIENTE ADD CONSTRAINT UN_PACIENTE_RG UNIQUE (NR_RG);
ALTER TABLE T_HC_MEDICO ADD CONSTRAINT UN_MEDICO_CRM UNIQUE (NR_CRM);
ALTER TABLE T_HC_TELEFONE ADD CONSTRAINT UN_TELEDONE_NUMERO UNIQUE (NR_TELEDONE);

-- ADICIONANDO AS CONSTRAINTS NOT NULL EM T_HC_PACIENTE
ALTER TABLE T_HC_PACIENTE MODIFY (NM_PACIENTE CONSTRAINT CK_NM_PACIENTE NOT NULL);
ALTER TABLE T_HC_PACIENTE MODIFY (NR_CPF CONSTRAINT CK_NR_CPF NOT NULL);
ALTER TABLE T_HC_PACIENTE MODIFY (NR_RG CONSTRAINT CK_NR_RG NOT NULL);
ALTER TABLE T_HC_PACIENTE MODIFY (NR_ALTURA CONSTRAINT CK_NR_ALTURA NOT NULL);
ALTER TABLE T_HC_PACIENTE MODIFY (NR_PESO CONSTRAINT CK_NR_PESO NOT NULL);
ALTER TABLE T_HC_PACIENTE MODIFY (DT_NASCIMENTO CONSTRAINT CK_DT_NASCIMENTO NOT NULL);
ALTER TABLE T_HC_PACIENTE MODIFY (DS_ESCOLARIDADE CONSTRAINT CK_DS_ESCOLARIDADE NOT NULL);
ALTER TABLE T_HC_PACIENTE MODIFY (DS_ESTADO_CIVIL CONSTRAINT CK_DS_ESTADO_CIVIL NOT NULL);

-- ADICIONANDO AS CONSTRAINTS NOT NULL EM T_HC_ENDERECO
ALTER TABLE T_HC_ENDERECO MODIFY (NM_LOGRADOURO CONSTRAINT CK_NM_LOGRADOURO NOT NULL);
ALTER TABLE T_HC_ENDERECO MODIFY (NR_LOGRADOURO CONSTRAINT CK_NR_LOGRADOURO NOT NULL);
ALTER TABLE T_HC_ENDERECO MODIFY (NR_CEP CONSTRAINT CK_NR_CEP NOT NULL);
ALTER TABLE T_HC_ENDERECO MODIFY (NM_BAIRRO CONSTRAINT CK_NM_BAIRRO NOT NULL);
ALTER TABLE T_HC_ENDERECO MODIFY (NM_CIDADE CONSTRAINT CK_NM_CIDADE NOT NULL);
ALTER TABLE T_HC_ENDERECO MODIFY (NM_ESTADO CONSTRAINT CK_NM_ESTADO NOT NULL);
ALTER TABLE T_HC_ENDERECO MODIFY (SG_ESTADO CONSTRAINT CK_SG_ESTADO NOT NULL);

-- ADICIONANDO AS CONSTRAINTS NOT NULL EM T_HC_TELEFONE
ALTER TABLE T_HC_TELEFONE MODIFY (NR_DDI CONSTRAINT CK_NR_DDI NOT NULL);
ALTER TABLE T_HC_TELEFONE MODIFY (NR_DDD CONSTRAINT CK_NR_DDD NOT NULL);
ALTER TABLE T_HC_TELEFONE MODIFY (NR_TELEDONE CONSTRAINT CK_NR_TELEDONE NOT NULL);

-- ADICIONANDO AS CONSTRAINTS NOT NULL EM T_HC_CONSULTA
ALTER TABLE T_HC_CONSULTA MODIFY (DT_HR_CONSULTA CONSTRAINT CK_DT_HR_CONSULTA NOT NULL);
ALTER TABLE T_HC_CONSULTA MODIFY (DS_MODALIDADE CONSTRAINT CK_DS_MODALIDADE NOT NULL);

-- ADICIONANDO AS CONSTRAINTS NOT NULL EM T_HC_MEDICO
ALTER TABLE T_HC_MEDICO MODIFY (NM_MEDICO CONSTRAINT CK_NM_MEDICO NOT NULL);
ALTER TABLE T_HC_MEDICO MODIFY (NR_CRM CONSTRAINT CK_NR_CRM NOT NULL);

-- ADICIONANDO AS CONSTRAINTS NOT NULL EM T_HC_CONEXAO
ALTER TABLE T_HC_CONEXAO MODIFY (TP_CONEXAO CONSTRAINT CK_TP_CONEXAO NOT NULL);

-- ADICIONANDO AS CONSTRAINTS NOT NULL EM T_HC_LEMBRETE
ALTER TABLE T_HC_LEMBRETE MODIFY (DT_HR_LEMBRETE CONSTRAINT CK_DT_HR_LEMBRETE NOT NULL);
ALTER TABLE T_HC_LEMBRETE MODIFY (DS_MENSAGEM CONSTRAINT CK_DS_MENSAGEM NOT NULL);

-- ADICIONANDO AS CONSTRAITS CHECK 

ALTER TABLE T_HC_ENDERECO ADD CONSTRAINT CK_SIGLA_ESTADO CHECK (SG_ESTADO IN ('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 
'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO'));
ALTER TABLE T_HC_TELEFONE ADD CONSTRAINT CK_DDI CHECK (NR_DDI = 55);
ALTER TABLE T_HC_TELEFONE ADD CONSTRAINT chk_nr_ddd CHECK (NR_DDD BETWEEN 11 AND 99);


SELECT * FROM T_HC_CONSULTA 


