-- DROP SEQUENCES
DROP SEQUENCE SEQ_T_HC_PACIENTE;
DROP SEQUENCE SEQ_T_HC_ENDERECO;
DROP SEQUENCE SEQ_T_HC_TELEFONE;
DROP SEQUENCE SEQ_T_HC_CONSULTA;
DROP SEQUENCE SEQ_T_HC_MEDICO;
DROP SEQUENCE SEQ_T_HC_LEMBRETE;
DROP SEQUENCE SEQ_T_HC_CONEXAO;

-- CREATE SEQUENCES
CREATE SEQUENCE SQ_T_HC_PACIENTE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_T_HC_ENDERECO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_T_HC_TELEFONE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_T_HC_CONSULTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_T_HC_MEDICO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_T_HC_LEMBRETE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SQ_T_HC_CONEXAO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


